/*
 * The ZLIB License
 *
 * Copyright 2018 Andrew Dean <me@ajdean.net>.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */
package net.ajdean.system;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import net.ajdean.system.obj.SystemProcess;

/**
 *
 * @author Andrew Dean <me@ajdean.net>
 */
public class ProcessViewer extends javax.swing.JFrame {
    private ArrayList<SystemProcess> processes;
    private DefaultListModel listModel;
    
    /**
     * Creates new form ProcessViewer
     */
    public ProcessViewer() {
        processes = new ArrayList();
        listModel = new DefaultListModel();
        initComponents();
        setProcessList();
    }
    
    /**
     * (Re)sets the processes list.
     */
    private void setProcessList() {
        System.out.println("Refresh");
        processes.clear();
        listModel.removeAllElements();
        
        try {
            processes = fetchProcesses();
            for (int i = 0; i < processes.size(); i++) {
                listModel.addElement(processes.get(i).getImageName());
            } 
        } catch (Exception ex) {
            Logger.getLogger(ProcessViewer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Gets the current system processes.
     * 
     * @return ArrayList
     * @throws IOException
     * @throws Exception
     */
    public ArrayList<SystemProcess> fetchProcesses() throws IOException, Exception {      
        ArrayList proc = new ArrayList();  
        
        Process cmd = new ProcessBuilder("tasklist.exe", "/fo", "csv", "/nh", "/v").start();

        new Thread(() -> {
            Scanner sc = new Scanner(cmd.getInputStream());
            if (sc.hasNextLine()) sc.nextLine();
            while (sc.hasNextLine()) {
                String line = sc.nextLine();
                String[] parts = line.split("\"*\",");
                for (int i = 0; i < parts.length; i++) { parts[i] = parts[i].replace("\"", ""); }
                
                proc.add(new SystemProcess(parts));
                
                //System.out.println(i + ": " + names[i] + " = " + parts[i]);
            }
        }).start();
        cmd.waitFor(); 
        
        return proc;
    }    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProcesses = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        txtImageName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtProcessID = new javax.swing.JTextField();
        txtSessionName = new javax.swing.JTextField();
        txtSessionID = new javax.swing.JTextField();
        txtMemory = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtCpuTime = new javax.swing.JTextField();
        txtWinTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Process Viewer");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lstProcesses.setBackground(new java.awt.Color(102, 102, 102));
        lstProcesses.setForeground(new java.awt.Color(204, 204, 204));
        lstProcesses.setModel(listModel);
        lstProcesses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstProcesses.setSelectionBackground(new java.awt.Color(204, 204, 204));
        lstProcesses.setSelectionForeground(new java.awt.Color(51, 51, 51));
        lstProcesses.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstProcesses);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        txtImageName.setBackground(new java.awt.Color(102, 102, 102));
        txtImageName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtImageName.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Image Name");

        txtProcessID.setBackground(new java.awt.Color(102, 102, 102));
        txtProcessID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtProcessID.setEnabled(false);

        txtSessionName.setBackground(new java.awt.Color(102, 102, 102));
        txtSessionName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtSessionName.setEnabled(false);

        txtSessionID.setBackground(new java.awt.Color(102, 102, 102));
        txtSessionID.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtSessionID.setEnabled(false);

        txtMemory.setBackground(new java.awt.Color(102, 102, 102));
        txtMemory.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtMemory.setEnabled(false);

        txtStatus.setBackground(new java.awt.Color(102, 102, 102));
        txtStatus.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtStatus.setEnabled(false);

        txtUserName.setBackground(new java.awt.Color(102, 102, 102));
        txtUserName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtUserName.setEnabled(false);

        txtCpuTime.setBackground(new java.awt.Color(102, 102, 102));
        txtCpuTime.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCpuTime.setEnabled(false);

        txtWinTitle.setBackground(new java.awt.Color(102, 102, 102));
        txtWinTitle.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtWinTitle.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Process ID");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Session Name");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Memory");

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Session ID");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Status");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("User Name");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("CPU Time");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Window Title");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtImageName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtProcessID)
                    .addComponent(txtSessionName)
                    .addComponent(txtSessionID)
                    .addComponent(txtMemory)
                    .addComponent(txtStatus)
                    .addComponent(txtUserName)
                    .addComponent(txtCpuTime)
                    .addComponent(txtWinTitle))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcessID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSessionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSessionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpuTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWinTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(4, 4, 4))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N

        btnExit.setBackground(new java.awt.Color(102, 102, 102));
        btnExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 204, 204));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.setContentAreaFilled(false);
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClicked(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(102, 102, 102));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(204, 204, 204));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setOpaque(true);
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setDetailInfo(int process) {
        if (process > -1) {
            SystemProcess sp = processes.get(process);
            txtImageName.setText(sp.getImageName());
            txtProcessID.setText(sp.getProccessID());
            txtSessionName.setText(sp.getSessionName());
            txtSessionID.setText(sp.getSessionID());
            txtMemory.setText(sp.getMemory());
            txtStatus.setText(sp.getStatus());
            txtUserName.setText(sp.getUserName());
            txtCpuTime.setText(sp.getCpuTime());
            txtWinTitle.setText(sp.getWindowTitle());
        } else {
            txtImageName.setText("");
            txtProcessID.setText("");
            txtSessionName.setText("");
            txtSessionID.setText("");
            txtMemory.setText("");
            txtStatus.setText("");
            txtUserName.setText("");
            txtCpuTime.setText("");
            txtWinTitle.setText("");
        }
    }
    
    private void lstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstValueChanged
        if (!lstProcesses.isSelectionEmpty()) {
            setDetailInfo(lstProcesses.getSelectedIndex());
            
            //btnMonitor.setEnabled(true);
            //btnKill.setEnabled(true);
        } else {
            setDetailInfo(-1);
            //btnMonitor.setEnabled(false);
            //btnKill.setEnabled(false);
        }
    }//GEN-LAST:event_lstValueChanged

    private void btnClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClicked
        JButton btn = (JButton) evt.getSource();
        
        if (btn == btnExit) {
            this.dispose();
        //} else if (btn == btnMonitor) {
            
        //} else if (btn == btnKill) {
            
        } else if (btn == btnRefresh) {
            setProcessList();
        }
    }//GEN-LAST:event_btnClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProcessViewer viewer = new ProcessViewer();
                viewer.setLocationRelativeTo(null);
                viewer.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstProcesses;
    private javax.swing.JTextField txtCpuTime;
    private javax.swing.JTextField txtImageName;
    private javax.swing.JTextField txtMemory;
    private javax.swing.JTextField txtProcessID;
    private javax.swing.JTextField txtSessionID;
    private javax.swing.JTextField txtSessionName;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtWinTitle;
    // End of variables declaration//GEN-END:variables
}
